---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echoapp-dev
  chart:
    git: git@github.com:nati-elmaliach/echoappConfig
    path: charts/echoapp
    ref: master
  values:
    image:
      repository: eu.gcr.io/future-depth-270520/echo-app
      tag: dev-hdtwcel9
    replicaCount: 1