---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ecoapp-stage
  namespace: stage
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stage-*
spec:
  releaseName: echoapp-stage
  chart:
    git: git@github.com:nati-elmaliach/echoappConfig.git
    path: charts/echoapp
    ref: master
  values:
    image:
      repository: eu.gcr.io/future-depth-270520/echoapp
      tag: latest
    configmap:
      PERSIST: true
      DBNAME: echo-staging
    service:
      name: echoapp-service-stage
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: www.stage.nati-echoapp.tk
          paths:
          - path: /
            backend:
              serviceName: echoapp-service-stage
              servicePort: 3000
    replicaCount: 1

