---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ecoapp-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: echoapp-prod
  chart:
    git: git@github.com:nati-elmaliach/echoappConfig.git
    path: charts/echoapp
    ref: master
  values:
    image:
      repository: eu.gcr.io/future-depth-270520/echoapp
      tag: 1.0.11
    configmap:
      PERSIST: true
    replicaCount: 1
