apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  PORT: {{ .Values.configmap.PORT }}
  LOGLEVEL: {{ .Values.configmap.LOGLEVEL }}
  {{- if .Values.configmap.PERSIST }}
  PERSIST: "true"
  {{- end }}
  DBNAME: {{ .Values.configmap.DBNAME }}

