{{- if .Values.dataBaseConnection.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-db-secret
type: Opaque
data:
  MONGODBURL: {{ .Values.mongosecret | b64enc }}
{{- end -}}